# Generated by Django 5.0.8 on 2024-08-26 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_updated_at_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='Users/covers/'),
        ),
    ]
