# Generated by Django 5.0.8 on 2024-09-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='product_quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
