# Generated by Django 5.0.8 on 2024-10-09 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='refund_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_number',
            field=models.CharField(default='237400001019', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
