# Generated by Django 5.0.8 on 2024-09-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_transaction_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('suspend', 'Suspend')], default='pending', max_length=10),
        ),
    ]
