# Generated by Django 5.0.8 on 2024-09-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('MTN', 'MTN Mobile Money'), ('ORANGE', 'Orange Money')], default='MTN', max_length=100),
        ),
    ]
